name: Deploy Hello-Kubernetes app

on:
  workflow_dispatch:
    inputs:
      clustername:
        description: 'Cluster Name'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Kubernetes Tools
      uses: yokawasa/action-setup-kube-tools@v0.11.1
      with:
        setup-tools: |
          kubectl

    - name: Get Kubernetes Credentials
      run: |
        mkdir -p ~/.kube
        VKE_CLUSTER_ID=$(curl --no-progress-meter -s -H "Authorization: Bearer ${{ secrets.VULTR_API_KEY }}" "https://api.vultr.com/v2/kubernetes/clusters" | jq -r '.vke_clusters[] | select(.label=="${{ github.event.inputs.clustername }}") | .id')
        curl --no-progress-meter -s -H "Authorization: Bearer ${{ secrets.VULTR_API_KEY }}" "https://api.vultr.com/v2/kubernetes/clusters/${VKE_CLUSTER_ID}/config" | jq -r '. | map_values(@base64d) | .kube_config' > ~/.kube/config 

    - name: Add helm repository to ArgoCD
      shell: bash
      run: |
        cat <<EOF | kubectl -n argocd apply -f -
        apiVersion: v1
        kind: Secret
        metadata:
          name: mobia-demo-repo
          namespace: argocd
          labels:
            argocd.argoproj.io/secret-type: repository
        data:
          sshPrivateKey: "$${ secrets.GH_SSH_KEY }}"
        stringData:
          url: git@github.com:rharisch/hello-kubernetes.git
          insecure: "true" # Do not perform a host key check for the server. Defaults to "false"
          enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"

    - name: Add application to ArgoCD
      shell: bash
      run: |
        cat <<EOF | kubectl -n argocd apply -f -
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: hello-kubernetes
            namespace: argocd
          spec:
            destination:
              namespace: demo-app
              server: https://kubernetes.default.svc
            project: default
            source:
              helm:
                valueFiles:
                - values.yaml
              path: charts/hello-kubernetes
              repoURL: git@github.com:rharisch/hello-kubernetes.git
              targetRevision: HEAD
          
